"""The OpenAPI document must describe the API-key protection the middleware applies.

WHAT WENT WRONG BEFORE THESE TESTS
----------------------------------
Runtime auth was correct and had always been correct: the middleware refused an
unauthenticated call with 401. But the generated OpenAPI document said nothing
about it, so Swagger rendered no Authorize button and every "Try it out" call
went out without ``X-API-Key`` and came back 401. The API looked broken to
anyone exploring it, while actually being right.

WHAT THESE TESTS PIN
--------------------
That the document and the middleware agree. The document is generated by asking
``requires_key`` - the same function the middleware calls - so the risk being
guarded against is not "the rules were copied wrong" but "the two stop being
wired to each other". A drift test therefore compares them directly, for every
operation, under both read policies.

None of this changes enforcement. Every test that asserts a status code below
asserts the same status code the API returned before this change.
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from erp_pipeline.api import ApiSettings, create_app
from erp_pipeline.api.main import API_KEY_SCHEME_NAME
from erp_pipeline.api.security import API_KEY_HEADER, requires_key

#: A stand-in for the operator's key. Never a real one, and asserted absent
#: from the generated document further down.
TEST_KEY = "OPENAPI_SCHEME_TEST_KEY_71104"

DOCUMENTED_METHODS = {"get", "post", "put", "delete", "patch"}


def spec_for(**settings):
    return create_app(settings=ApiSettings(**settings)).openapi()


def operations(spec):
    """Every (method, path, operation) the document declares."""
    for path, item in spec.get("paths", {}).items():
        for method, operation in item.items():
            if method in DOCUMENTED_METHODS:
                yield method, path, operation


@pytest.fixture
def protected_spec():
    """The deployed Azure shape: a key is set and reads are protected."""
    return spec_for(api_key=TEST_KEY, protect_reads=True)


# ----------------------------------------------------------------------
# The scheme itself
# ----------------------------------------------------------------------


class TestTheSecuritySchemeIsDeclared:
    def test_the_document_declares_an_api_key_scheme(self, protected_spec):
        schemes = protected_spec["components"]["securitySchemes"]

        assert API_KEY_SCHEME_NAME in schemes

    def test_the_scheme_is_an_api_key_in_a_header(self, protected_spec):
        scheme = protected_spec["components"]["securitySchemes"][API_KEY_SCHEME_NAME]

        assert scheme["type"] == "apiKey"
        assert scheme["in"] == "header"

    def test_the_header_name_matches_the_one_the_middleware_reads(
        self, protected_spec
    ):
        """The document must name the header the middleware actually checks.

        A document advertising ``Authorization`` while the middleware reads
        ``X-API-Key`` would send Swagger users to a 401 with no explanation.
        """
        scheme = protected_spec["components"]["securitySchemes"][API_KEY_SCHEME_NAME]

        assert scheme["name"] == API_KEY_HEADER == "X-API-Key"

    def test_the_scheme_is_declared_even_when_no_key_is_configured(self):
        """The header is part of the contract regardless of this deployment.

        Declared always, REQUIRED only when the middleware would enforce it -
        which the next class checks.
        """
        schemes = spec_for()["components"]["securitySchemes"]

        assert API_KEY_SCHEME_NAME in schemes


# ----------------------------------------------------------------------
# Which operations claim protection
# ----------------------------------------------------------------------


class TestTheDocumentMatchesTheMiddleware:
    @pytest.mark.parametrize("protect_reads", [True, False])
    def test_every_operation_agrees_with_requires_key(self, protect_reads):
        """The drift test. One comparison per operation, both read policies."""
        spec = spec_for(api_key=TEST_KEY, protect_reads=protect_reads)
        disagreements = []

        for method, path, operation in operations(spec):
            documented = bool(operation.get("security"))
            enforced = requires_key(method, path, protect_reads)

            if documented != enforced:
                disagreements.append(
                    f"{method.upper()} {path}: document says "
                    f"{'protected' if documented else 'public'}, middleware "
                    f"says {'protected' if enforced else 'public'}"
                )

        assert disagreements == [], "\n".join(disagreements)

    def test_protected_operations_reference_the_declared_scheme(
        self, protected_spec
    ):
        """A requirement naming an undeclared scheme renders no Authorize button."""
        declared = set(protected_spec["components"]["securitySchemes"])

        for method, path, operation in operations(protected_spec):
            for requirement in operation.get("security", []):
                for name in requirement:
                    assert name in declared, f"{method.upper()} {path} -> {name}"

    def test_capabilities_is_protected_when_reads_are_protected(
        self, protected_spec
    ):
        """The exact endpoint that sent people to Swagger confused."""
        operation = protected_spec["paths"]["/v1/capabilities"]["get"]

        assert operation.get("security") == [{API_KEY_SCHEME_NAME: []}]

    def test_capabilities_is_public_when_reads_are_not_protected(self):
        spec = spec_for(api_key=TEST_KEY, protect_reads=False)

        assert not spec["paths"]["/v1/capabilities"]["get"].get("security")

    def test_a_mutating_route_is_protected_under_either_read_policy(self):
        for protect_reads in (True, False):
            spec = spec_for(api_key=TEST_KEY, protect_reads=protect_reads)
            operation = spec["paths"]["/v1/responses/adapt"]["post"]

            assert operation.get("security"), f"protect_reads={protect_reads}"

    def test_health_routes_are_never_marked_protected(self, protected_spec):
        """Deliberately unauthenticated, even with reads protected."""
        for path in ("/v1/health/live", "/v1/health/ready"):
            operation = protected_spec["paths"][path]["get"]

            assert not operation.get("security"), f"{path} was marked protected"

    def test_nothing_is_marked_protected_when_no_key_is_configured(self):
        """With no key the middleware enforces nothing, so nor does the document.

        Claiming protection that is not applied is the more dangerous direction
        of the two: it invites an operator to believe a route is guarded.
        """
        spec = spec_for()

        claimed = [
            f"{method.upper()} {path}"
            for method, path, operation in operations(spec)
            if operation.get("security")
        ]

        assert claimed == []


# ----------------------------------------------------------------------
# The key must not reach the document
# ----------------------------------------------------------------------


class TestTheKeyNeverReachesTheDocument:
    def test_the_configured_key_is_absent_from_the_whole_document(
        self, protected_spec
    ):
        import json

        assert TEST_KEY not in json.dumps(protected_spec)

    def test_the_scheme_carries_no_default_or_example_value(self, protected_spec):
        scheme = protected_spec["components"]["securitySchemes"][API_KEY_SCHEME_NAME]

        assert "default" not in scheme
        assert "example" not in scheme
        assert TEST_KEY not in str(scheme)

    def test_the_served_openapi_endpoint_contains_no_key(self):
        app = create_app(settings=ApiSettings(api_key=TEST_KEY, protect_reads=True))

        with TestClient(app) as client:
            body = client.get("/openapi.json").text

        assert TEST_KEY not in body


# ----------------------------------------------------------------------
# Enforcement is unchanged
# ----------------------------------------------------------------------


class TestRuntimeBehaviourIsUnchanged:
    """The middleware is still the only thing that decides. These assertions
    are the same ones that held before the document was annotated."""

    @pytest.fixture
    def client(self):
        app = create_app(settings=ApiSettings(api_key=TEST_KEY, protect_reads=True))

        with TestClient(app) as test_client:
            yield test_client

    def test_a_protected_read_without_a_key_is_still_401(self, client):
        assert client.get("/v1/capabilities").status_code == 401

    def test_a_protected_read_with_a_wrong_key_is_still_401(self, client):
        response = client.get(
            "/v1/capabilities", headers={API_KEY_HEADER: "not-the-key"}
        )

        assert response.status_code == 401

    def test_a_protected_read_with_the_valid_key_succeeds(self, client):
        response = client.get(
            "/v1/capabilities", headers={API_KEY_HEADER: TEST_KEY}
        )

        assert response.status_code == 200

    def test_a_mutating_route_without_a_key_is_still_401(self, client):
        assert client.post("/v1/search", json={"query": "x"}).status_code == 401

    def test_health_is_still_reachable_without_a_key(self, client):
        assert client.get("/v1/health/live").status_code == 200

    def test_the_openapi_document_itself_stays_public(self, client):
        """Swagger cannot render an Authorize button it is not allowed to fetch."""
        assert client.get("/openapi.json").status_code == 200
        assert client.get("/docs").status_code == 200

    def test_annotation_did_not_introduce_a_second_auth_path(self, client):
        """No dependency was added, so an unauthenticated call still reaches the
        middleware's own 401 body rather than FastAPI's dependency error."""
        body = client.get("/v1/capabilities").json()

        assert body["success"] is False
        assert body["error"]["code"]
        assert "request_id" in body["error"]
